### ISSUE TITLE
Disabled select can be opened

### ISSUE THREAD

**Issue by VincentCharpentier** [wiredjs/wired-elements#10]
I was on the showcase (https://wiredjs.com/showcase.html) in the wired-combo section and I noticed that the disabled element can be opened if you click on its small triangle. It seems like a bug to me.

Just wanted to let you know
Really nice work btw

**Comment by pshihn** [comment]
Resolved by https://github.com/wiredjs/wired-combo/commit/b2ce1f632a28cdc04df2ab266560bac3e06440e8
