### ISSUE TITLE
Allow using classes instead of custom elements.

### ISSUE THREAD

**Issue by abalter** [wiredjs/wired-elements#109]
The Wordpress page/post editor strips unfamiliar elements such as `<wired-button>`. This is probably the situation in other places as well. It would be nice to be able to simply class an element. Moreover, it would be swell if this could implement creating rough borders.

For example:

```
<button class='wired-button', data-wired="{elevation: 3; stroke=2; fill='#ABC'}"></button>
```

**Comment by pshihn** [comment]
Not sure this is easy to do as described. 
Perhaps can develop an independent script that replaces dives with a certain attribute with an element.

**Comment by abalter** [comment]
Hmmm. I see what you mean.

**Comment by pshihn** [comment]
Not in scope of this project
