### ISSUE TITLE
Adopt monorepo structure

### ISSUE THREAD

**Issue by dhruvdutt** [wiredjs/wired-elements#11]
The current setup is each component has its own standalone package.
We should think about adopting monorepo structure where we would have to maintain only one repo. This makes maintenance and debugging better and easier.

I would love to contribute adopting monorepo or yarn workspaces for the project.

**Comment by pshihn** [comment]
That is in the plans. The reason for multi repo was that's what is (was?) needed for webcomponents.org

**Comment by dhruvdutt** [comment]
Alright. Can we keep this issue open and track the monorepo plan here?

**Comment by pshihn** [comment]
https://github.com/wiredjs/wired-elements is now a monorepo.
