### ISSUE TITLE
Bundled file missing

### ISSUE THREAD

**Issue by mkalam-alami** [wiredjs/wired-elements#112]
Since the 2.0.0 alphas, there's no longer a `wired-elements.bundled.js` file in the releases, meaning the https://unpkg.com/wired-elements@latest/dist/wired-elements.bundled.js link in the Readme is dead.

The raw JS build is perfect to hack together some HTML into fun-looking wireframes, it would be great not to drop the support.

Thanks for the great lib!

**Comment by Mashiane** [comment]
It would be nice to have a post that can indicate on how to compile these as a bundle. Can someone please advise? Thanks

**Comment by MarcSkovMadsen** [comment]
I would also need this. Could you please distribute a bunddle. Thanks.

**Comment by pshihn** [comment]
My bad. URL to use is https://unpkg.com/wired-elements@2.0.3/lib/wired-elements-bundled.js
live example: https://glitch.com/~wired-elements-vanilla

If you need a CJS version: https://unpkg.com/wired-elements@2.0.3/lib/wired-elements-bundled.cjs.js

These are all part of the npm package for wired-elements

**Comment by pshihn** [comment]
Sorry, https://unpkg.com/wired-elements@2.0.5/lib/wired-elements-bundled.js is the latest
