### ISSUE TITLE
Feature request: add a variable font that mimics handwriting

### ISSUE THREAD

**Issue by webxl** [wiredjs/wired-elements#12]
I couldn't find any, but perhaps someone is working on this. It would give an extra level of randomness/uniqueness to the mockups.

**Comment by pshihn** [comment]
Yes that would be amazing. I'v been meaning to look into variable fonts. Sp little time!
I'm hoping someone may step in.

**Comment by anooppoommen** [comment]
could you elaborate on what the feature is supposed to be 
and if it's up for grabs i would love to try to implement it

**Comment by pshihn** [comment]
I'm actually not sure about this. What I really want here is to first figure out if we can create a Variable font here that adds randomness to the rendering. I have not created a variable font before, so I wanted someone who knows about this and let me know the feasibility of a task like that.

**Comment by aturingmachine** [comment]
Could a potential solution be to not use variable fonts and instead use a font with multiple alternates for characters? I do not know much about fonts/typefaces so I am just spit-balling. This could potentially create the hand written effect while maintaining a sort of psuedo-randomness.

**Comment by pshihn** [comment]
@aturingmachine that's true. That is why, in some way, it is out of the scope of this project.

These elements inherit the font being used can be changes via normal CSS. So the user can already pick what font they want to use and may decide to choose a variable or a font with alternates. 

[wiredjs.com](https://wiredjs.com) uses a handwritten styled font from google fonts.
