### ISSUE TITLE
Add tabs programmatically

### ISSUE THREAD

**Issue by mrosi** [wiredjs/wired-elements#125]
Hi,
I would like to manipulate Tabs programatically - does exist any API to add, delete, select tabs?
Are there any events I can listen to?
Thanks a lot for any info
Martin R.

**Comment by apennamen** [comment]
Hi Martin,
So if I understand well, you want to do something like this (not a complete working example)
```javascript
const tabs = document.getElementsByTagName('wired-tabs')[0];
const newTab = document.createElement('wired-tab');
tabs.appendChild(newTab)
```

The DOM API is normally enoug to be able to do what you asked without adding those methods to the component ?
Regards

**Comment by mrosi** [comment]
yes, it's something I expected but it didn't work at the first touch ... I've moved from pure JS to VueJS framework, so that a lot of things works in other way
Thanks a lot for your answer
Martin R.
