### ISSUE TITLE
Accessibility for components

### ISSUE THREAD

**Issue by jpnelson** [wiredjs/wired-elements#13]
Would a PR be accepted that added accessible outlines, tab navigation and screen readability to these components?

**Comment by pshihn** [comment]
Sure. I may not be able to pull it in quite yet though. Planning some major code chaange to make it work with react. Also planning to create a mono repo for ease : https://github.com/wiredjs/wired-elements/issues/11 
I think it would be much easier to accept PRs after that is done.

**Comment by pshihn** [comment]
Related: https://github.com/wiredjs/wired-toggle/issues/4

**Comment by pshihn** [comment]
All the components are in a monorepo now! I may not have time to work on these in the near future, so any help with accessibility is welcome.

**Comment by pshihn** [comment]
Button accessibility added by https://github.com/wiredjs/wired-elements/pull/28
Slider accessibility added by https://github.com/wiredjs/wired-elements/pull/35

**Comment by pshihn** [comment]
With https://github.com/wiredjs/wired-elements/pull/41 all components are now accessible.
