### ISSUE TITLE
CDN not working 

### ISSUE THREAD

**Issue by samwelkinuthia** [wiredjs/wired-elements#142]
Unable to load wired elements through CDN. Error message: Cannot find "/dist/wired-elements.bundled.js" in wired-elements@2.0.5

**Comment by apennamen** [comment]
Hello,
Doc has to be updated, CDN is:
https://unpkg.com/wired-elements@latest/lib/wired-elements-bundled.js

#126 
#130

**Comment by samwelkinuthia** [comment]
Thank you!
