### ISSUE TITLE
in Firefox - Error: customElements is not defined

### ISSUE THREAD

**Issue by eklem** [wiredjs/wired-elements#18]
Firefox Quantum 60.0.1 (64-bits)

[...]
Error in 0.5.2/wired-button.js (86:1)
customElements is not defined
[...]

<img width="1295" alt="screen shot 2018-05-30 at 08 56 00" src="https://user-images.githubusercontent.com/236656/40704521-a3192a88-63e8-11e8-9d0b-79d997ad5ec3.png">

Apart from that: Nice project =)

**Comment by pshihn** [comment]
Well we know this works in Firefox (e.g controls on https://wiredjs.com/)

I believe it's StackBlitz issue, they are loading the polyfills required for Web components in a lazy fashion. If you hit the refresh button in the right panel, it loads sometimes. 

Here's a JS Fiddle version that works: https://jsfiddle.net/7za6zvmd/

**Comment by eklem** [comment]
Thanks!
