### ISSUE TITLE
Can't change width

### ISSUE THREAD

**Issue by reversd1** [wiredjs/wired-elements#185]
I can't manually change the width of a dialog without adding more text. 
This is the dialog: 
```
<wired-dialog id="dialog1">
    <p id="content1">

    </p>
    <wired-input id="name-input" ></wired-input>
    <div style="text-align: right; padding: 30px 16px 16px;">
      <wired-button id="closeDialog">Done</wired-button>
    </div>
  </wired-dialog>
```
and this is the CSS:

```
#dialog1 {
  width:150px;
  height:120px;
}
#name-input {
 width:150px; 
}

```
and even with adding more text, the input still is not as wide as intended.

**Comment by zippyfish** [comment]
Up

**Comment by reversd1** [comment]
Update: I changed the width of the text container and for some reason adding ```position:absolute``` to the input allows for changing the width.
