### ISSUE TITLE
error : Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by ddv12138** [wiredjs/wired-elements#19]
when i use it in chrome 67.0.3396.62, it report error from console that " Relative references must start with either "/", "./", or "../". "
my web server is tomcat 
i hope u can fixed all "import" Sentence

**Comment by pshihn** [comment]
One need to package the modules to get all the relative paths straight. 

I have now included a pre-bundled release of all elements found in the dist folder (https://github.com/wiredjs/wired-elements/tree/master/packages/all/dist) 

Or you can just use it from the CDN
```html
<script src="https://unpkg.com/wired-elements@latest/dist/wired-elements.bundled.min.js"></script>
```

**Comment by ddv12138** [comment]
thank
