### ISSUE TITLE
in Firefox: TypeError: Error resolving module specifier: @polymer/lit-element/lit-element.js

### ISSUE THREAD

**Issue by mrvary** [wiredjs/wired-elements#20]
I am trying to use the wired-checkbox-Element, but ran into a few problems. Would love to use those, because I think wired-elements look pretty neat :)

## 1. Version -> TypeError

Installed with `npm i wired-checkbox` and copied the tag. _Btw, I think it would be nicer if the path would include the node-modules directory, so you don't have work it out yourself ..._

The HTML looks like this: 
```
<html` lang="en">
<head>
  <meta charset="UTF-8">
  <script type="module" src="node_modules/wired-checkbox/wired-checkbox.js"></script>
</head>
<body>
  <wired-checkbox text="Checkbox One"></wired-checkbox>
</body>
</html>
```

When I open it up in the Browser the console logs **TypeError: Error resolving module specifier: @polymer/lit-element/lit-element.js**

## 2. Version -> ReferenceError

I looked for known Issues and stumbled upon [this one](https://github.com/wiredjs/wired-elements/issues/18). 
After copying `<script type="module" src="https://unpkg.com/wired-button@latest/wired-button.js?module"></script>` from the jsfiddle sample (which works) and changing it to be `wired-checkbox` it throws **Reference Error: customElements is not defined**

**Comment by pshihn** [comment]
There are a couple of issues here. The modules use NPM notation to refer to dependencies. So they need to be either packaged using webpack or rollup, or alternatively use polymer-cli to serve which automatically resolves this. See. https://github.com/Polymer/lit-element#getting-started

However, to get things started, I now provide a prepackaged build for all elements:
In the [dist folder](https://github.com/wiredjs/wired-elements/tree/master/packages/all/dist) or from CDN:

```html
<script src="https://unpkg.com/wired-elements@latest/dist/wired-elements.bundled.min.js"></script>
```

Regarding your second error: For firefox, and IE you need to include a polyfill
```html
<script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.0.0/webcomponents-loader.js"></script>
```

So your final code in the header looks like:
```html
<script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.0.0/webcomponents-loader.js"></script>
<script src="https://unpkg.com/wired-elements@latest/dist/wired-elements.bundled.min.js"></script>
```

**Comment by pshihn** [comment]
Here's a fiddle for you: https://jsfiddle.net/shihn/wo9pdsxh/1/

**Comment by mrvary** [comment]
works like a charm, thank you!
