### ISSUE TITLE
wired-input with v-model

### ISSUE THREAD

**Issue by flacito** [wiredjs/wired-elements#24]
I might be making a newbie mistake but when I try to use wired-input connected with v-model in vuejs the model isn't updating.

https://jsfiddle.net/flacito/x9bta40r/23/

**Comment by pshihn** [comment]
I'm not sure how v-model works. I'm assuming it's trying to link to some events that a regular input fires but it's not getting from wired-input. (Likely the `input` event). 
What's probably happening is that the input event from the underlying control is not bubbling past the shadowDom of wired-input.

**Comment by pshihn** [comment]
Ah.. .ignore the above comment. 
There's a bug where the value specified as an attribute will not get set.

Following does not work:
```html
<wired-input id="wi" value="Hello world"></wired-input>
```
But done through javascript works
```javascript
document.getElementById('wi').value = "Hello World";
```

**Comment by flacito** [comment]
🙏 for the quick response...   looking forward to your progress

**Comment by pshihn** [comment]
I've fixed the code so that following works:
```html
<wired-input id="wi" value="Hello world"></wired-input>
```
But, it does not solve your v-model issues. I'll have to look into how v-model works. I was hoping that fixing the former will automatically solve this issue.

**Comment by pshihn** [comment]
@flacito I looked at the vue documentation here: https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components

Seems like, for custom components, you need to bind like this:
```html
<wired-input type="text" v-bind:value="n2" v-on:input="n2 = $event.target.value"></wired-input>
```

Note that `v-on:input` bit is only if you'd like to double bind it. 

Here's a fork of your example with my latest fix and custom binding: https://jsfiddle.net/shihn/8fdmrgq1/

**Comment by flacito** [comment]
Thanks for the extra help @pshihn and thanks for the merge.  🙏   The wired look is already proving to be an impresser with my colleagues at my day job.  Thanks again!  --Brian
