### ISSUE TITLE
why no support vue.js

### ISSUE THREAD

**Issue by fanxinjie** [wiredjs/wired-elements#26]
I really want to use the wired.js component in the vue.js project. Can I support it?

**Comment by HintikkaKimmo** [comment]
Actually looking for something. I am going to try using https://github.com/vuejs/vue-web-component-wrapper to make them work this weekend. I will report how it goes. 

That whole wrapper library is based on this approach https://alligator.io/vuejs/vue-integrate-web-components/ but fixes few rough edges.

**Comment by pshihn** [comment]
The simplest way to get started with vue, is to just use the pre-packaged version
```html
<script src="https://unpkg.com/wired-elements@0.6.4/dist/wired-elements.bundled.min.js"></script>
```

Here's an example of using components in vue with v-model binding:
https://jsfiddle.net/shihn/8b9svwro/

Hope it helps

**Comment by fanxinjie** [comment]
Sorry for not responding to you in a timely manner, the error when I use this component in the project is as follows:
![image](https://user-images.githubusercontent.com/23193063/41187131-e1167012-6bd5-11e8-8d8f-ba7551d41747.png)
I did not find any solution,can you help me?

**Comment by fanxinjie** [comment]
Sorry to bother you for so long and the problem has been solved. Thank you

**Comment by pshihn** [comment]
@fanxinjie Glad it worked out. What was the problem? Maybe I can improve the documentation

**Comment by fanxinjie** [comment]
@pshihn Sorry, due to the exam leads only to see your message today.
The error has always been because the first component that I used to reference on demand failed. I converted to reference directly in the index.html file through the CDN. At this time, I forgot to remove the previous on-demand reference registration assembly code.
Another problem is that referencing components on demand fails.
