### ISSUE TITLE
playground error

### ISSUE THREAD

**Issue by tigercosmos** [wiredjs/wired-elements#27]
https://stackblitz.com/edit/wired-elements?file=index.html
```
Error in 0.6.0/wired-button.js (86:1)
customElements is not defined
Evaluating https://unpkg.com/wired-button@0.6.0/wired-button.js
Evaluating https://unpkg.com/wired-elements@0.6.1/wired-elements.js
Evaluating index.js
Booting application
```

**Comment by pshihn** [comment]
This is actually a bug i StackBlitz when loading polyfills on Firefox, IE. 
Should work fine one Chrome:

Here's jfiddle link that should work for you: https://jsfiddle.net/shihn/7ft5by3g/
