### ISSUE TITLE
wired-slider cut off in Chrome

### ISSUE THREAD

**Issue by melanieseltzer** [wiredjs/wired-elements#30]
Tested in Firefox/Safari/Chrome on Mac and could only see it in Chrome (67.0.3396.87).

Slider circle seems to be cut in half randomly at its left-most position. Doesn't seem to happen at its right-most position.

![kapture 2018-06-13 at 16 49 15](https://user-images.githubusercontent.com/17421347/41384484-efcdaa8c-6f2a-11e8-9eb9-9c43783fc325.gif)

**Comment by pshihn** [comment]
I believe this was resolved in later builds.
