### ISSUE TITLE
wired-card calls non-existing this._requestRender()

### ISSUE THREAD

**Issue by balloob** [wiredjs/wired-elements#31]
`<wired-card>` calls `this._requestRender()` when the `slotchange` event is fired. However, that method does not exist on the elemnt.

https://github.com/wiredjs/wired-elements/blob/da4f150c04a336df41e228b794f14663f54b6d6f/packages/wired-card/wired-card.js#L55

`<wired-card>` depends on Lit Element `^0.5.1`. I've checked the source code of Lit Element, and it looks like they renamed it to `this.requestRender()`:

https://github.com/Polymer/lit-element/blob/fb90e7640777cab01c9eac2006cde558c34b041d/src/lit-element.ts#L261

(I did a quick search and noticed a few more places that call `_requestRender()`.

I was using `<wired-card>` by importing it form unpkg:

```html
<script type='module' src='https://unpkg.com/wired-card@0.6.0/wired-card.js?module'></script>
```

**Comment by pshihn** [comment]
Sure enough, lit-element changed their API in 0.5.2 and that version is getting picked up. They should have used 0.6 for breaking changes fo semVer to work. 
In the short term, if you can explicitly depend on lit-element 0.5.1, you may avoid running into this issue.

**Comment by pshihn** [comment]
Resolved by upgrading to latest lit-element and adjusting code accordingly: 
https://github.com/wiredjs/wired-elements/pull/32

Fix in v0.6.5

**Comment by balloob** [comment]
Thanks 🙂

Now featuring Wired JS in the custom cards example for Home Assistant https://developers.home-assistant.io/docs/en/lovelace_custom_card.html#defining-your-card

**Comment by pshihn** [comment]
@balloob looks cool
