### ISSUE TITLE
Changing to wired breaks Joomla

### ISSUE THREAD

**Issue by StarAzure** [wiredjs/wired-elements#33]
I am using this in a custom Joomla template but changing "input" to "wired-input" breaks Joomla form. Joomla expects < input >.  Is there a way I can achieve the wired effect by using a css class instead of changing them to "wired-***" ?

**Comment by StarAzure** [comment]
Joomla does not recognize wired-input as an input.

See example - http://sketch.starazure.com  > Joomla > Login

If you try to login using username: admin and password: admin it thinks the fields are empty.

Also in the page - http://sketch.starazure.com/index.php/joomla/register
If you try to register it thinks all fields are empty.

If I change wired-input to "input" it works.

So back to my question - Is there a way I can use wired styles without changing my inputs to wired-inputs ? Ideally a css class would be more ideal.

I am kind of stuck because my theme is based on hang drawn elements and found this as its almost ready to be released.

**Comment by pshihn** [comment]
Checkout https://www.getpapercss.com i think that may suit you well

**Comment by StarAzure** [comment]
That is a great alternative. Too bad I could not use Wired JS but thanks for the alternate solution.

**Comment by pshihn** [comment]
I'm sure with further investigation we could solve the Joomla issue as well. If I were to take a hunch, Joomla is scanning for particular tag names. Or it has some issues with shadowdom/custom elements.

**Comment by StarAzure** [comment]
This could be the issue:

In my php file, the input is:

`<wired-input class="form-control" type="text" name="username" id="username" value="" size="25" required="" aria-required="true" autofocus="">
</wired-input>`

When it gets rendered, I see there is another input that gets generated inside wired-input with a different id as shown below:

`<input id="txt" type="text" required="" autofocus="" size="25">`

**Comment by pshihn** [comment]
That input is inside a Shadow DOM, so it's protected. How do you tell Joomla what controls to use for the form? Or does it pick them up automatically?

**Comment by StarAzure** [comment]
This is how Joomla renders a field:
In my login php file, it calls the form field type 
`<?php echo $field->input; ?>`

The in my form field text.php file I have this:
`<input class="form-control" type="text" name="<?php
echo $name; ?>" id="<?php
echo $id; ?>" <?php
echo $dirname; ?> value="<?php
echo htmlspecialchars($value, ENT_COMPAT, 'UTF-8'); ?>" <?php echo implode(' ', $attributes); ?> />`

**I have a work around but does not work for emails**
I did this 
`<wired-input type="text">
<input class="form-control" type="text" name="<?php
echo $name; ?>" id="<?php
echo $id; ?>" <?php
echo $dirname; ?> value="<?php
echo htmlspecialchars($value, ENT_COMPAT, 'UTF-8'); ?>" <?php echo implode(' ', $attributes); ?> />
</wired-input>
` 
This worked BUT it wanted to show a tooltip with error, I get javascript errors:
`An invalid form control with name='jform[name]' is not focusable.
register:1 An invalid form control with name='jform[username]' is not focusable.
register:1 An invalid form control with name='jform[email1]' is not focusable.`

**Comment by pshihn** [comment]
Seem like you or joomla is adding an input control as a child of wired-element. You don't need to do that. Wired-input creates an input element automatically inside a `shadow-root`. So now there are 2 inputs. I assume joomla is asking that inserted input for the value rather than asking the value from wired-input.

**Comment by StarAzure** [comment]
I just tried another option but that did not work either. Joomla still does not recognize it as an input.

I used jQuery as shown below.

Php file:

`<input type="password" class="form-control wired"`


JQuery:

`$(function () {
  'use strict'
	$(".wired").replaceWith(function() { return "<wired-input>" + this.innerHTML + "</wired-input>"; });

})
`

Result:

![wired](https://user-images.githubusercontent.com/12852059/41883456-a71e438c-78bc-11e8-92fa-e058933530ad.jpg)



When I remove the jQuery, thus removing wired-input, it works but as expected its not a wired input.

![wired2](https://user-images.githubusercontent.com/12852059/41883527-0773d058-78bd-11e8-8066-5adb358a2ba6.jpg)

**Comment by pshihn** [comment]
I think the main problem here is that wired-input does not have the `form-control` class on it.  
I don't see the code where you are inserting the wired-input. How are you defining it. Maybe add that class name?

**Comment by StarAzure** [comment]
`form-control` is just a Bootstrap class. It was adding an additional border and css properties so I had removed it. I added it back but it has no impact. Still facing the same issue.

![wired3](https://user-images.githubusercontent.com/12852059/41943364-206335e0-7971-11e8-87cf-34e1d959cd69.jpg)

**Comment by pshihn** [comment]
I did some reading, and I think what I'll have to do is pass the `name` property from wired-input to the underlying input control.

**Comment by pshihn** [comment]
I just released a new build. 
Try v0.6.7 see if it helps.
https://unpkg.com/wired-elements@0.6.7/dist/wired-elements.bundled.js

**Comment by StarAzure** [comment]
I already use `https://unpkg.com/wired-elements@latest/dist/wired-elements.bundled.min.js`

It does not work and still says empty password. 

Thanks for trying.

**Comment by pshihn** [comment]
can you check if the <input> inside your <wired-element> has a `name` attribute set?

**Comment by pshihn** [comment]
Never mind, I just saw your site, and see that it is being set. Not sure what else to do here, and I dont really fancy learning joomla t the moment. :/

**Comment by StarAzure** [comment]
I understand. I don't know what to do either.
