### ISSUE TITLE
Not working on IE11

### ISSUE THREAD

**Issue by motss** [wiredjs/wired-elements#36]
Is this due to `lit-html` not supporting IE11 in some edge cases?

**Comment by pshihn** [comment]
I don't know.  I haven't tested on IE11 yet :/

**Comment by hoangph271** [comment]
> I don't know. I haven't tested on IE11 yet :/

Please don't...!
Let the devil rest...!

**Comment by motss** [comment]
It should work now after a year. `lit-html` was not supporting IE11 at that time but it is no longer the case now.
