### ISSUE TITLE
Error: customElements is not defined

### ISSUE THREAD

**Issue by jokerreton** [wiredjs/wired-elements#38]
when I type this to import WiredCard:
`import { WiredCard } from "wired-card";`
there are a error in FF:
`ReferenceError: customElements is not defined`
but totally normal operation in chrome.

I am sure the error is caused by `wired-js`:
`customElements.define('wired-card', WiredCard);`

what can I do to solve it?thanks!

**Comment by jokerreton** [comment]
and I found that wired-card can't inherit property `height`...
daughter element can't set height by percentage

**Comment by pshihn** [comment]
Regarding your Firefox issue, you need to include a polyfill for web components

add following to your `head` tag before wired-elements

```html
<script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.0.0-beta.3/webcomponents-loader.js"></script>
```

**Comment by pshihn** [comment]
regarding the `wired-card` issue - it is true. The size is computed dynamically. When there's nested cards, it may not compute the size correctly at load time. 

you can try calling the `requestRender()` method on the card when you think it's all ready to force a recompute.

**Comment by jokerreton** [comment]
yep，thanks！

But `webcomponentsjs@2.0.0` still makes some error in FF.So I change it to 2.0.2 version.

`<script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.0.2/webcomponents-loader.js"></script>` 

then I fixed it.
