### ISSUE TITLE
Hello how to ?

### ISSUE THREAD

**Issue by Vlad412** [wiredjs/wired-elements#40]
Hello idk if this is the right place, but how to use this ? :S I'm pretty confused I thought it was as simple as the readme x))

Thanks and have a nice day

**Comment by pshihn** [comment]
Simplest way to get started quickly:

Add following script tags (First one is a polyfill - not needed in chrome):
```html
<script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.0.2/webcomponents-loader.js"></script>
<script src="https://unpkg.com/wired-elements@0.6.7/dist/wired-elements.bundled.min.js"></script>
```

and then:
```html
<wired-input placeholder="Enter name"></wired-input>
<wired-button>Submit</wired-button>
```

Here's a jsfiddle for this: https://jsfiddle.net/shihn/7ft5by3g/
