### ISSUE TITLE
How to make it compatible with Firefox browser

### ISSUE THREAD

**Issue by qiushuiqs** [wiredjs/wired-elements#44]
window.ShadyCSS.prepareTemplateDom is not a function

**Comment by qiushuiqs** [comment]
window.ShadyCSS.prepareTemplateDom is not a function

**Comment by pshihn** [comment]
You need to load a polyfill.
Following will do the trick:
```html
<script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.0.3/webcomponents-bundle.js"></script>
```

See: https://github.com/wiredjs/wired-elements/issues/38
and https://www.webcomponents.org/polyfills for more info
