### ISSUE TITLE
How to resize buttons

### ISSUE THREAD

**Issue by aayusharora** [wiredjs/wired-elements#46]
After using the wired-button, I realized the button width and height is a fixed path.
How can I change the width of the button?

**Comment by pshihn** [comment]
you can set a size  using CSS just like any other element.

```html
<style>
  .large {
    width: 100px;
    height: 80px;
  }
</style>
<wired-button class="large">Button 2</wired-button>
```

Here's a live example: https://jsfiddle.net/shihn/exu0joL1/3/

**Comment by aayusharora** [comment]
Thanks a lot @pshihn
