### ISSUE TITLE
Every elements in the demo has a focus ring

### ISSUE THREAD

**Issue by binhbbbb** [wiredjs/wired-elements#47]
It seems that every wired element I tested has a focus ring. It goes away when I add `outline: none;`. Is this a problem or is it intended?

**Comment by pshihn** [comment]
It wasn't there at first, but it was added to make the controls compatible with standard accessibility requirements (https://github.com/wiredjs/wired-elements/issues/13). In the future, the ring could be replaced with an alternative stroke color. 

But, if you don't want the focus ring, as you suggested, an `outline:none` will do the trick

**Comment by binhbbbb** [comment]
I see. Thanks for clarifying. It would be good to have this info public in the website or in the repo README as well.

**Comment by pshihn** [comment]
Will update. Reopening issue so docs get updated.

**Comment by pshihn** [comment]
The new version (0.8.0) has better focus indication.
