### ISSUE TITLE
No sketch displayed

### ISSUE THREAD

**Issue by binhbbbb** [wiredjs/wired-elements#48]
On Chrome, Opera & Safari. It loads up with no sketch displayed, only when I started clicking the item.

https://codepen.io/binhbbbb/pen/MENdqK?editors=1000

**Comment by pshihn** [comment]
Thanks for reporting this. It's a rendering race condition. 

In the meantime, the fix is to call `requestRender()` on the control to force a render.

**Comment by binhbbbb** [comment]
I see, will this get fixed in the future. And also a noobish question, how do I call `requestRender()`, can you make some modifications in the codepen or something?

**Comment by pshihn** [comment]
I'll fix it this weekend. 

Here's your pen modified with the fix: https://codepen.io/shihn/pen/mjKboK
Custom elements are like any other elements. Just get a reference (like `getElementById()`) and call any method or set any property. See the JS section of the pen

**Comment by pshihn** [comment]
Fixed by https://github.com/wiredjs/wired-elements/pull/49
Available in 0.7.2

**Comment by binhbbbb** [comment]
Awesome. Thanks a lot!
