### ISSUE TITLE
Suggestion: make button backgrounds look "colored in"🖌

### ISSUE THREAD

**Issue by acobster** [wiredjs/wired-elements#5]
It'd be cool if there were an option for `wired-button` and similar elements with solid background colors to render the background as an svg path that looks like a thick pen/brush stroke, rather than a solid rectangle. I think this would help it feel a lot "sketchier."

Thanks for making these awesome components! :smile:

**Comment by pshihn** [comment]
Good idea. Probably could borrow hachure filling from from http://roughjs.com/

**Comment by pshihn** [comment]
Not the background color, but the 'selected' items in combo, listboxes, tabs now show sketchier backgrounds.
Adding sketchier backgrounds to all controls may make them less flexible. 
For selected items though, it was a good upgrade.
