### ISSUE TITLE
Using with React

### ISSUE THREAD

**Issue by hugozap** [wiredjs/wired-elements#6]
I tried importing a wired element but React throws an error:

NotSupportedError
Failed to construct 'CustomElement': The result must not have attributes

https://codesandbox.io/s/pp4q7kw9q7

Do I need to do something else to make it compatible with react? thanks!

**Comment by pshihn** [comment]
I may be able to look at this later. but top of my head, I  think that you may need to build your project to be es2015 compliant rather than es5 to work with web components.

**Comment by pshihn** [comment]
You may also need to add an es-5 adapter in your html file. 
<script src="https://rawgit.com/webcomponents/webcomponentsjs/master/custom-elements-es5-adapter.js"></script>

But you run into the next issue, as described in: https://github.com/Polymer/lit-element/issues/72

Anyways, still investigating

**Comment by pshihn** [comment]
I think there's a bit more to resolve than just the class name in the constructor. 
Btw, it may resolve your issue by moving `pending` to connectedCallback but it will defeat the purpose of it. In Lit-Element the _firstRendered/_didRender is called  in the super's connectedcallback. I remove the `pending` class name in the _didRender method. 

A better solution would be to set it in the _render() method only if it's the first time.

**Comment by pshihn** [comment]
I have made all components compatible with React (and hopefully Vue too).

Here's a demo of it working with react: https://stackblitz.com/edit/wired-elements-react?file=index.js

**Comment by pshihn** [comment]
One thing to keep in mind with react is one needs an es5 polyfill for web components.

```
<script src="node_modules/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js"></script>
```

**Comment by hugozap** [comment]
Awesome! Thanks a lot @pshihn .

**Comment by alessandro308** [comment]
I've tried to add a custom-elements-es5-adapter.js to my project (I have uploaded it on another server then linked as script src in my index). But the problem is not resolved.

`import React, { Component } from 'react';
import './App.css';
import "wired-elements"
class App extends Component {
  render() {
    return (
      <div className="App">
        <nav>
                <wired-listbox horizontal selected="two">
                    <wired-item value="apps" text="APPS"></wired-item>
                    <wired-item value="devices" text="DEVICES"></wired-item>
                    <wired-item value="settings" text="SETTINGS"></wired-item>
                </wired-listbox>
          </nav>
      </div>
    );
  }
}

export default App;`

And then the error `NotSupportedError: Failed to construct 'CustomElement': The result must not have attributes`

**Comment by alessandro308** [comment]
> I have made all components compatible with React (and hopefully Vue too).
> 
> Here's a demo of it working with react: https://stackblitz.com/edit/wired-elements-react?file=index.js

Oh, and this demo doesn't work anymore :)

**Comment by pshihn** [comment]
@alessandro308  Is that happening on StackBlitz or any online editor or in your own local dev environment? I know that with he latest version of Wired-Elements there's an issue where it does not work on StackBlitz.

**Comment by alessandro308** [comment]
@pshihn I'm using a local environment created with `create-react-app`. Sometimes the already reported error appears, someother times `Uncaught TypeError: Class constructor Ve cannot be invoked without 'new'` is reported in the console.

**Comment by pshihn** [comment]
I have not tried `create-react-app`  with this. They have presets on how they build the projects which may not be compatible. 
In the mean time what you can do is not `import` them in your project but use a pre-built version on page. 
Add the following to your HTML
`<script src="https://unpkg.com/wired-elements@latest/dist/wired-elements.bundled.min.js"></script>
`
after the webcomponents-loader.js

**Comment by pshihn** [comment]
Of course you could use your local `wired-elements.bundled.min.js` not the one served with unpkg

**Comment by alessandro308** [comment]
I've tried to add the following scripts to the HTML page:
```html
<script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.0.0/webcomponents-loader.js"></script>
    <script src="https://unpkg.com/wired-elements@latest/dist/wired-elements.bundled.min.js"></script> 
```
And then I'm using directly the wired-elements without including them in Javascript.

The error is not resolved... `NotSupportedError: Failed to construct 'CustomElement': The result must not have attributes`

**Comment by pshihn** [comment]
Ugh. I was hoping it would be simple as that. I know there are some quirks to making web components working with react. I haven't done much creact-react-app but will look into this weekend. I have to get to the bottom of it eventually And will get back to you.

**Comment by tscholl2** [comment]
I have some more info that may or may not be relevant since I also ran into this issue (but not with react).

My `index.html` file is:
```
<!DOCTYPE html>
<html>
<head>
  <script src="https://unpkg.com/wired-elements@0.7.2/dist/wired-elements.bundled.min.js"></script>
</head>
</html>
```
Loading this page and opening a console you can use `document.createElement("wired-button")` and it works (on Chrome 70 at least). However, when I bump the version to `0.8.0-0` it fails with the error:

![image](https://user-images.githubusercontent.com/8905985/49527415-b01f6400-f866-11e8-8c65-d39aab5fcfae.png)

If I get more time later this week I may try to dig into what exactly changed, but if you could point to some release notes if you have any that would be greatly appreciated.

Thank you for such a neat component library!
