### ISSUE TITLE
wired-slider drag issue on firefox

### ISSUE THREAD

**Issue by PabloGancharov** [wiredjs/wired-elements#7]
Firefox version 60.0.1 (64-bit)
Slider drag feature presents a buggy behavior:

![dragissue](https://user-images.githubusercontent.com/1298917/40520311-905894a2-5f9b-11e8-895b-dadd27558dda.gif)

The same component works fine in chrome

**Comment by pshihn** [comment]
Same issue as : https://github.com/wiredjs/wired-slider/issues/3

**Comment by pshihn** [comment]
Fixed in v0.5.5 of wired-slider
https://github.com/wiredjs/wired-slider/commit/13fd11eb3203c20f5e5dd460df629cd7c93709bd
