### ISSUE TITLE
New Control - Tabs

### ISSUE THREAD

**Issue by pshihn** [wiredjs/wired-elements#71]

**Comment by aadamsx** [comment]
Wow, Tabs too!!  This lib is awsome!

**Comment by pshihn** [comment]
@aadamsx Yes tabs are just proposed at the moment. If you can think of other controls that would be nice as sketchy widgets, let me know

**Comment by aadamsx** [comment]
@pshihn, sure, I added a few suggestions!  Can't wait to see what you do with this lib!

**Comment by pshihn** [comment]
Tabs are now supported with this: https://github.com/wiredjs/wired-elements/pull/91
