### ISSUE TITLE
New control: Header Navigation bar 

### ISSUE THREAD

**Issue by aadamsx** [wiredjs/wired-elements#73]
I think a navigation header, with a few dropdowns on the right and something on the left, with the option to colapse into a menu dropdown as you see on mobile, would be nice control to have.  

Again, I don't know if this is appropriate for a self-contained control, but I sure wish it was because I always seem to spend time on these in the past.

**Comment by pshihn** [comment]
I tihnk this could be achieved manually by someone using wired-elements. There's nothing 'sketchy' about the rendering of the toolbar but the controls in it.
