### ISSUE TITLE
New controls: bar/line/circle/pie chart

### ISSUE THREAD

**Issue by aadamsx** [wiredjs/wired-elements#76]
I don't know if charting is on the table or not, but these charting controls are useful.

**Comment by pshihn** [comment]
This would nice to have at some point - but I think there are other charting libs out there that do sketchy charts using https://roughjs.com
Keeping this issue open though

**Comment by pshihn** [comment]
out of scope for now. There are other libs like https://github.com/jwilber/roughViz that do this
