### ISSUE TITLE
New control: Range silder

### ISSUE THREAD

**Issue by aadamsx** [wiredjs/wired-elements#79]
Instead of a signle point slider, a range slider with two points is sometimes a nice option.

See this: https://materializecss.com/range.html

**Comment by abdiG** [comment]
Hey @aadamsx , may i work on this if it's not worked on?.

**Comment by pshihn** [comment]
@abdiG  There's already a slider: https://github.com/wiredjs/wired-elements/tree/master/packages/wired-slider 

You can either enhance that slider to have two points or create a new one independently.

**Comment by abdiG** [comment]
Thank you @pshihn. I will enhance it to include two points.

**Comment by abdiG** [comment]
Hey @pshihn , im stuck on setting up the project. I have followed `README.md` and `Dev Environment`. I added `<wired-slider></wired-slider>`
    `<wired-slider disabled></wired-slider>`
    `<wired-slider knobradius="15" value="10" min="5" max="15"></wired-slider>` and included `<script type="module" src="wired-slider/wired-slider.js"></script>` into `slider.html`, but i can't see an output when i run the project.
