### ISSUE TITLE
CodePen friendly packages would be great

### ISSUE THREAD

**Issue by japboy** [wiredjs/wired-elements#8]
Just like LitElement's [official demo at CodePen](https://codepen.io/sorvell/pen/BxZgPN), it would be great to try it out out of the box, this great wired-elements, without downloading packages, setting up local development environments, etc..

LitElements provides its built assets within its repository so I can just use them from CodePen with unpkg.com CDN.

it would be great if wired-elements also provides the same way :D

**Comment by pshihn** [comment]
Good idea. Here's https://jsfiddle.net/7za6zvmd/ to start something

**Comment by pshihn** [comment]
Added playgrounds on readme and the main website:

[Wired Elements playground](https://stackblitz.com/edit/wired-elements?file=index.html)

[Wired Elements in React playground](https://stackblitz.com/edit/wired-elements-react?file=index.js)
