### ISSUE TITLE
New control: Preloader

### ISSUE THREAD

**Issue by aadamsx** [wiredjs/wired-elements#82]
You have a progress bar, but this is a preloader and shows of course something is happening... 

Reference: https://materializecss.com/preloader.html

**Comment by SahibArora** [comment]
Hi there,
I was trying to understand the Project, 
First of all, I really like it, thought to contribute to it as well,
I see that, you are using react to make them look like hand-written, but with styles in the class, there are many other functions too, 
But over here, which functions will be required in preloader is not described, or I didn't understand.
Can you please tell more, how can I create the preloader in wired way!

**Comment by SahibArora** [comment]
What I understand is 
1. Create a folder in the packages with the name of lets say wired-preloader.
2. Install the packages necessary for coding.
3. Code the React class for that (Question is here) - {With the style what are the other functions necessary as coded in other classes}.
Thank you!

**Comment by pshihn** [comment]
@SahibArora Sorry the code is not well organized.  This might help: https://github.com/wiredjs/wired-elements/wiki/Dev-Environment though I need to document event further.
Also, this is not a react library. The components are written as custom-elements so they are framework free.

**Comment by pshihn** [comment]
Since this issue is related to Preloader..
Progress and spinner were added in https://github.com/wiredjs/wired-elements/pull/93 
and will be available in 1.0. I think that satisfies this feature request.
