### ISSUE TITLE
Textarea with default value simply broken

### ISSUE THREAD

**Issue by kokarn** [wiredjs/wired-elements#84]
I have a super simple test page that doesn't behave even close to what I'd expect.

```
<!DOCTYPE html>
<head>
    <title>
        Test page
    </title>
</head>
<body>
    <wired-textarea rows=10 value="some test"></wired-textarea>
    <script src="https://unpkg.com/wired-elements@latest/dist/wired-elements.bundled.min.js"></script>
```

This creates the very strange looking
![screenshot 2018-10-08 at 17 19 17](https://user-images.githubusercontent.com/1373940/46617931-5f1d1900-cb1e-11e8-807b-9ab396a32116.png)
with the following markup
```
<textarea id="textarea" autocomplete="undefined" inputmode="undefined" placeholder="undefined" rows="10" minlength="undefined" maxlength="undefined"></textarea>
```
that has a couple of issues.

1) It's not rendered correctly in regards to the number of rows
2) It displays the text `undefined` for the placeholder
3) It removes the value specified for the content

PS: Side note, there's usually no `value` attribute for textarea, as it uses the contents of the HTML element instead.

**Comment by aadamsx** [comment]
https://stackblitz.com/ example please?  

You can even fork one of mine to get started: https://stackblitz.com/edit/lit-element-wired-elements

**Comment by pshihn** [comment]
oops closed too soon. Wanted to confirm before closing

**Comment by pshihn** [comment]
As for `value` attribute. I realize textarea uses innerHtml to initialize the value but it's always been a very spotty interface. It doesn't get updated at all and is only used to initialize the value. 
There was no reason why wired-textarea had to behave exactly the same. It doesn't in many other ways as well. e.g, it auto grows in size.

**Comment by pshihn** [comment]
Here's a working example with the fix: https://wiredjs.github.io/wired-elements/examples/textarea.html
