### ISSUE TITLE
docs unclear on native events (dispatched or not)

### ISSUE THREAD

**Issue by ducin** [wiredjs/wired-elements#86]
example: Input.
In the github docs section, there's no information on the native `change` being fired. I couldn't believe that such event is not triggered and so I started to read the source and I found an implementation of `_onChange` that - probably, not sure - reemits `change` event.

Is there any general rule for re-emitting events that I missed? Are you mentioning in the docs only additional (custom wired-elements) events? And guarantee to re-emit all native ones?

**Comment by pshihn** [comment]
I have updated the docs. 
For all input based controls, native events are also fired.
