### ISSUE TITLE
Error "Failed to construct 'CustomElement'"

### ISSUE THREAD

**Issue by Nudelsieb** [wiredjs/wired-elements#87]
The complete error is

`Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes`

I have no idea how to fix this. A bit of background: I just tried to use some components and according to the docs it is very easy by adding it as dependency to index.html, e.g. like 
`<script src="https://unpkg.com/wired-elements@latest/dist/wired-elements.bundled.min.js"></script>` inside the head.

I want to use it for a demo inside a stencil component. Maybe it clashes with Stencil's polyfils?

**Comment by asfktz** [comment]
Same here.

Seems like a bug version `0.8.0`+,
`0.7.2` Works fine.

https://stackblitz.com/edit/wired-elements-react-cc6ukn?file=package.json

**Comment by pshihn** [comment]
There's no reason why these should not work with stencil. 
I haven't had a chance to work on in this this year, getting back to it this weekend. Stay tuned!

**Comment by jeasonstudio** [comment]
+1

**Comment by pshihn** [comment]
This should be resolved in the latest release.  (0.9.x)
The problem was an attribute was being set after creating the shadow root. 
This did not create an issue in older versions of lit-element.
