### ISSUE TITLE
Default value for wired-slider

### ISSUE THREAD

**Issue by pvictor** [wiredjs/wired-elements#96]
Hello,

The default value for the slider doesn't seem to be taken into account, see in home page https://wiredjs.com/ despite `value="33"` slider is at `0`.

Thanks!

**Comment by pshihn** [comment]
Oops. Thanks for reporting.

**Comment by hoangph271** [comment]
If we change the value property, wired-slider isn't affected at all, as well.

**Comment by pshihn** [comment]
Resolved in the code. Will be fixed in v2.0.0 coming out this week
